title: "ARYX Co."
description: "Independent digital studio building niche content platforms."
url: "https://aryxco.github.io"
baseurl: ""

author:
  name: "Aryx K."

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Plugins
plugins: []
